### ISSUE TITLE
Question: Is whereby Open source software

### ISSUE THREAD

**Issue by inet56** [whereby/dev-docs#17]
I couldn't find its source code.

**Comment by odinho** [comment]
Hi!

It's not :) It is a service, so it's not meant to run it yourself, but rather use what we provide and set up. That is our product. There exists other tools you can self-host if that is what you were thinking of. If there's a bug you'd want to fix or something like this, you'll have to tell support and we'd need to prioritize internally etc.

Hope that answers your question.

Odin
